// Code generated by "stringer -type=TokenKind"; DO NOT EDIT.

package lexer

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EOF-0]
	_ = x[ADVANTAGE-1]
	_ = x[DISADVANTAGE-2]
	_ = x[DIE-3]
	_ = x[FACES-4]
	_ = x[QUANTITY-5]
	_ = x[ADDITION-6]
	_ = x[SUBTRACTION-7]
	_ = x[EXPLODE-8]
}

const _TokenKind_name = "EOFADVANTAGEDISADVANTAGEDIEFACESQUANTITYADDITIONSUBTRACTIONEXPLODE"

var _TokenKind_index = [...]uint8{0, 3, 12, 24, 27, 32, 40, 48, 59, 66}

func (i TokenKind) String() string {
	if i < 0 || i >= TokenKind(len(_TokenKind_index)-1) {
		return "TokenKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenKind_name[_TokenKind_index[i]:_TokenKind_index[i+1]]
}
